language: node_js
cache: npm
node_js:
  - lts/*
before_install:
  - rvm install 2.6.0

install:
  - npm ci
  - bundle install

script:
  - npm t
  - npm run build:api-markup
  - npm run webpack:prod
  - bundle exec jekyll build