# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# this is the folder that contains all the source files for the site
# to keep things tidy we separate this from the rest of the config dfiles
source: _source
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Basil.js reference
email: fabianmoronzirfas@protonmail.ch
description: > # this means to ignore newlines until "baseurl:"
  This is the genereated reference for basil.js
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://basiljs.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: basil_js
github_username:  basiljs

# sass:
#     style: compressed
#     sass_dir: _sass
# Build settings
markdown: kramdown
# kramdown:
#     smart_quotes: ["apos", "apos", "quot", "quot"]
highlighter: rouge
plugins:
  - jekyll-feed
exclude:
  - assets/ts
  - Gemfile
  - Gemfile.lock
  - package.json
  - .bin/
  - lib/
  - node_modules
  - test/
  - assets/js/src/
  - .cache/
  - webpack.config/
  - bootstrap-scripts/

webrick:
  headers:
    Access-Control-Allow-Origin: "*"